import type { RatherDeck } from "./types";

export const ratherDecks: RatherDeck[] = [
  {
    slug: "general",
    title: "General Mayhem",
    description: "Classic dilemmas that reveal who you really are",
    icon: "🎲",
    summary: {
      wildTitle: "Agent of Chaos",
      wildDescription: "You picked the wild option most of the time. Rules are just suggestions to you.",
      safeTitle: "Steady Eddie",
      safeDescription: "You played it safe more often than not. Smart? Maybe. Boring? Never.",
      balancedTitle: "The Contradictor",
      balancedDescription: "You went back and forth like a pendulum. Even you don't know what you want.",
    },
    questions: [
      { id: "g1", optionA: "Always be 10 minutes late", optionB: "Always be 2 hours early", wildSide: "a" },
      { id: "g2", optionA: "Live without music forever", optionB: "Live without movies forever", wildSide: "b" },
      { id: "g3", optionA: "Have a rewind button for life", optionB: "Have a pause button for life", wildSide: "b" },
      { id: "g4", optionA: "Always know what people are thinking", optionB: "Always be able to read the future", wildSide: "a" },
      { id: "g5", optionA: "Fight one horse-sized duck", optionB: "Fight 100 duck-sized horses", wildSide: "a" },
      { id: "g6", optionA: "Never use social media again", optionB: "Never watch TV again", wildSide: "a" },
      { id: "g7", optionA: "Have unlimited money but no friends", optionB: "Have unlimited friends but no money", wildSide: "a" },
      { id: "g8", optionA: "Be famous for something embarrassing", optionB: "Be anonymous forever", wildSide: "a" },
      { id: "g9", optionA: "Eat only pizza for the rest of your life", optionB: "Never eat pizza again", wildSide: "b" },
      { id: "g10", optionA: "Live in a castle but it is always cold", optionB: "Live in a tent but it is always warm", wildSide: "b" },
      { id: "g11", optionA: "Have a time machine that only goes backward", optionB: "Have a time machine that only goes forward", wildSide: "b" },
      { id: "g12", optionA: "Always tell the truth and people hate you", optionB: "Always lie and people love you", wildSide: "b" },
      { id: "g13", optionA: "Be able to fly but only 3 feet off the ground", optionB: "Be able to teleport but only to places you have been", wildSide: "a" },
      { id: "g14", optionA: "Have a personal chef forever", optionB: "Have a personal driver forever", wildSide: "b" },
      { id: "g15", optionA: "Give up your phone for a year", optionB: "Give up your best friend for a year", wildSide: "b" },
      { id: "g16", optionA: "Live in the past forever", optionB: "Live in the future forever", wildSide: "b" },
      { id: "g17", optionA: "Have unlimited power but be alone", optionB: "Have no power but be surrounded by love", wildSide: "a" },
      { id: "g18", optionA: "Always sweat profusely when nervous", optionB: "Always hiccup when lying", wildSide: "a" },
      { id: "g19", optionA: "Speak every language fluently", optionB: "Play every instrument perfectly", wildSide: "a" },
      { id: "g20", optionA: "Be rich and ugly", optionB: "Be poor and gorgeous", wildSide: "b" },
      { id: "g21", optionA: "Never have to sleep again", optionB: "Never have to eat again", wildSide: "a" },
      { id: "g22", optionA: "Have a photographic memory", optionB: "Have a genius-level IQ", wildSide: "a" },
      { id: "g23", optionA: "Always get a table at any restaurant", optionB: "Never wait in any line again", wildSide: "a" },
      { id: "g24", optionA: "Live without air conditioning forever", optionB: "Live without heating forever", wildSide: "b" },
    ],
  },
  {
    slug: "extreme",
    title: "No Middle Ground",
    description: "Absurd extremes. Pick your poison.",
    icon: "🔥",
    summary: {
      wildTitle: "Certified Unhinged",
      wildDescription: "You chose the chaotic option over and over. Therapists would have a field day.",
      safeTitle: "Surprisingly Tame",
      safeDescription: "You played it safer than expected. The chaos gods are disappointed.",
      balancedTitle: "Perfectly Balanced",
      balancedDescription: "You toggled between chaos and calm like a seasoned diplomat.",
    },
    questions: [
      { id: "e1", optionA: "Have to shout everything you say", optionB: "Have to whisper everything you say", wildSide: "a" },
      { id: "e2", optionA: "Fight a bear with a pool noodle", optionB: "Fight a shark with a pool noodle", wildSide: "b" },
      { id: "e3", optionA: "Be trapped in a room with 100 cats", optionB: "Be trapped in a room with 100 parrots", wildSide: "b" },
      { id: "e4", optionA: "Have a permanent clown face", optionB: "Have permanent clown shoes", wildSide: "b" },
      { id: "e5", optionA: "Sneeze glitter forever", optionB: "Sneeze confetti forever", wildSide: "a" },
      { id: "e6", optionA: "Have your every sneeze sound like a trombone", optionB: "Have your every yodel sound like a sneeze", wildSide: "a" },
      { id: "e7", optionA: "Never use a door again — always climb through windows", optionB: "Never use stairs again — always slide down banisters", wildSide: "a" },
      { id: "e8", optionA: "Have a tail that wags when happy", optionB: "Have ears that flop when excited", wildSide: "a" },
      { id: "e9", optionA: "Only be able to communicate through song", optionB: "Only be able to communicate through interpretive dance", wildSide: "b" },
      { id: "e10", optionA: "Have a rewind button but it only works on embarrassing moments", optionB: "Have a fast-forward button but only for boring meetings", wildSide: "b" },
      { id: "e11", optionA: "Live in a giant shoe", optionB: "Live in a giant teapot", wildSide: "a" },
      { id: "e12", optionA: "Be chased by a duck every day", optionB: "Be chased by a goose every day", wildSide: "b" },
      { id: "e13", optionA: "Have hot dog fingers", optionB: "Have spaghetti for hair", wildSide: "b" },
      { id: "e14", optionA: "Only eat food that is green", optionB: "Only eat food that is orange", wildSide: "b" },
      { id: "e15", optionA: "Have a ringtone that is just you screaming", optionB: "Have a ringtone that is you laughing maniacally", wildSide: "a" },
      { id: "e16", optionA: "Be able to talk to squirrels but they are rude", optionB: "Be able to talk to pigeons but they gossip about you", wildSide: "b" },
      { id: "e17", optionA: "Have hiccups that make a trumpet sound", optionB: "Have hiccups that make a fart sound", wildSide: "a" },
      { id: "e18", optionA: "Have to moonwalk everywhere", optionB: "Have to cartwheel everywhere", wildSide: "b" },
      { id: "e19", optionA: "Wear a clown wig to every formal event", optionB: "Wear flip-flops to every formal event", wildSide: "a" },
      { id: "e20", optionA: "Every door you open plays a fanfare", optionB: "Every door you open plays a sad trombone", wildSide: "a" },
      { id: "e21", optionA: "Have a tiny T-Rex arm for the rest of your life", optionB: "Have baby legs for the rest of your life", wildSide: "a" },
      { id: "e22", optionA: "Always smell like wet dog", optionB: "Always smell like old cheese", wildSide: "a" },
      { id: "e23", optionA: "Have to do a little dance before entering any room", optionB: "Have to sing before entering any room", wildSide: "b" },
      { id: "e24", optionA: "Be haunted by a friendly ghost who tells bad jokes", optionB: "Be followed by a raccoon that judges you silently", wildSide: "b" },
    ],
  },
  {
    slug: "food",
    title: "Food Fights",
    description: "For the foodies, the picky eaters, and everyone in between",
    icon: "🍕",
    summary: {
      wildTitle: "Culinary Daredevil",
      wildDescription: "You picked the wild food option every time. Your taste buds fear nothing.",
      safeTitle: "Classic Palate",
      safeDescription: "You stuck with the safe choices. Nothing wrong with knowing what you like.",
      balancedTitle: "Fork in the Road",
      balancedDescription: "You could not decide between adventure and comfort. Relatable.",
    },
    questions: [
      { id: "f1", optionA: "Eat only sweet food forever", optionB: "Eat only savory food forever", wildSide: "b" },
      { id: "f2", optionA: "Put pineapple on every pizza", optionB: "Put anchovies on every pizza", wildSide: "b" },
      { id: "f3", optionA: "Never eat breakfast again", optionB: "Never eat dessert again", wildSide: "a" },
      { id: "f4", optionA: "Only eat food cooked by a Michelin chef", optionB: "Only eat food cooked by yourself", wildSide: "b" },
      { id: "f5", optionA: "Have unlimited sushi for life", optionB: "Have unlimited tacos for life", wildSide: "b" },
      { id: "f6", optionA: "Put ketchup on everything", optionB: "Put hot sauce on everything", wildSide: "b" },
      { id: "f7", optionA: "Eat the same meal every day forever", optionB: "Eat something different every day but never your favorite", wildSide: "b" },
      { id: "f8", optionA: "Have a chef who only makes pasta", optionB: "Have a chef who only makes sushi", wildSide: "a" },
      { id: "f9", optionA: "Eat cereal with water instead of milk", optionB: "Eat pizza folded in half like a taco", wildSide: "a" },
      { id: "f10", optionA: "Never eat chocolate again", optionB: "Never eat cheese again", wildSide: "a" },
      { id: "f11", optionA: "Have a bottomless cup of coffee", optionB: "Have a bottomless plate of cookies", wildSide: "b" },
      { id: "f12", optionA: "Only eat food that is blue", optionB: "Only eat food that is red", wildSide: "a" },
      { id: "f13", optionA: "Put whipped cream on steak", optionB: "Put gravy on ice cream", wildSide: "b" },
      { id: "f14", optionA: "Be able to summon any dish by snapping your fingers", optionB: "Be able to taste food through your fingertips", wildSide: "b" },
      { id: "f15", optionA: "Have a fridge that restocks itself", optionB: "Have a stove that cooks anything perfectly", wildSide: "b" },
      { id: "f16", optionA: "Only eat at 5-star restaurants", optionB: "Only eat street food from around the world", wildSide: "b" },
      { id: "f17", optionA: "Give up coffee for a year", optionB: "Give up sugar for a year", wildSide: "a" },
      { id: "f18", optionA: "Eat food that is always too hot", optionB: "Eat food that is always too cold", wildSide: "a" },
      { id: "f19", optionA: "Have a personal pizza oven", optionB: "Have a personal ice cream maker", wildSide: "b" },
      { id: "f20", optionA: "Only eat breakfast foods", optionB: "Only eat dinner foods", wildSide: "a" },
      { id: "f21", optionA: "Drink only smoothies for hydration", optionB: "Drink only broth for hydration", wildSide: "b" },
      { id: "f22", optionA: "Have to eat food with chopsticks forever", optionB: "Have to eat food with a spork forever", wildSide: "b" },
    ],
  },
  {
    slug: "life",
    title: "Life Choices",
    description: "The big decisions that say a lot about you",
    icon: "🌱",
    summary: {
      wildTitle: "Thrill Seeker",
      wildDescription: "You chose the adventurous path every time. YOLO is your middle name.",
      safeTitle: "Comfort Zone Champion",
      safeDescription: "You know what you want and you stick with it. Consistency is underrated.",
      balancedTitle: "The Weigher",
      balancedDescription: "You carefully considered each option. Both sides had their appeal.",
    },
    questions: [
      { id: "l1", optionA: "Have a guaranteed job for life", optionB: "Have unlimited potential but no guarantee", wildSide: "b" },
      { id: "l2", optionA: "Live in the city", optionB: "Live in the countryside", wildSide: "b" },
      { id: "l3", optionA: "Travel the world for a year", optionB: "Buy your dream house", wildSide: "a" },
      { id: "l4", optionA: "Have a 4-day work week", optionB: "Have a 6-hour work day", wildSide: "a" },
      { id: "l5", optionA: "Retire at 50 with modest savings", optionB: "Retire at 70 with a fortune", wildSide: "a" },
      { id: "l6", optionA: "Always work from home", optionB: "Always work from a cool office", wildSide: "b" },
      { id: "l7", optionA: "Have a time machine", optionB: "Have a teleportation device", wildSide: "b" },
      { id: "l8", optionA: "Know exactly how you will die", optionB: "Know exactly when you will die", wildSide: "a" },
      { id: "l9", optionA: "Be famous for 15 minutes", optionB: "Be a legend after you die", wildSide: "b" },
      { id: "l10", optionA: "Live the same day over and over", optionB: "Live a random day each day", wildSide: "b" },
      { id: "l11", optionA: "Have your dream job but low pay", optionB: "Have a boring job but amazing pay", wildSide: "a" },
      { id: "l12", optionA: "Be able to speak to animals", optionB: "Be able to speak every human language", wildSide: "a" },
      { id: "l13", optionA: "Always find parking", optionB: "Never wait in a line again", wildSide: "a" },
      { id: "l14", optionA: "Have unlimited streaming subscriptions", optionB: "Have unlimited concert tickets", wildSide: "b" },
      { id: "l15", optionA: "Live near the beach", optionB: "Live near the mountains", wildSide: "b" },
      { id: "l16", optionA: "Have a personal assistant for life", optionB: "Have a personal chef for life", wildSide: "a" },
      { id: "l17", optionA: "Be a morning person", optionB: "Be a night owl", wildSide: "b" },
      { id: "l18", optionA: "Always have great Wi-Fi", optionB: "Always have a great playlist", wildSide: "a" },
      { id: "l19", optionA: "Read every book ever written", optionB: "Watch every movie ever made", wildSide: "b" },
      { id: "l20", optionA: "Live without the internet", optionB: "Live without air travel", wildSide: "a" },
    ],
  },
  {
    slug: "social",
    title: "Social Dilemmas",
    description: "Relationships, friendships, and social chaos",
    icon: "💬",
    summary: {
      wildTitle: "Social Butterfly on Fire",
      wildDescription: "You went for the bold social choice every time. People either love or fear you.",
      safeTitle: "The People Pleaser",
      safeDescription: "You chose the harmonious option. Conflict avoidance is an art form.",
      balancedTitle: "Social Shapeshifter",
      balancedDescription: "You adapted to each scenario. Chameleon energy detected.",
    },
    questions: [
      { id: "s1", optionA: "Always be honest and hurt feelings", optionB: "Always lie to protect feelings", wildSide: "a" },
      { id: "s2", optionA: "Have 100 surface-level friends", optionB: "Have 3 deeply loyal friends", wildSide: "a" },
      { id: "s3", optionA: "Always say what you are thinking", optionB: "Always know what others are thinking", wildSide: "a" },
      { id: "s4", optionA: "Be the life of every party", optionB: "Be the one everyone confides in", wildSide: "a" },
      { id: "s5", optionA: "Have a best friend who lives far away", optionB: "Have a decent friend who lives next door", wildSide: "a" },
      { id: "s6", optionA: "Always be the funniest person in the room", optionB: "Always be the smartest person in the room", wildSide: "a" },
      { id: "s7", optionA: "Never be able to use sarcasm again", optionB: "Never be able to give compliments again", wildSide: "b" },
      { id: "s8", optionA: "Have a group chat that is always active", optionB: "Have a group chat that is always silent", wildSide: "a" },
      { id: "s9", optionA: "Be invited to every party but leave early", optionB: "Be invited to fewer parties but stay late", wildSide: "a" },
      { id: "s10", optionA: "Always arrive fashionably late", optionB: "Always be the first one there", wildSide: "a" },
      { id: "s11", optionA: "Have a roommate who is messy but fun", optionB: "Have a roommate who is neat but boring", wildSide: "a" },
      { id: "s12", optionA: "Always pick the restaurant", optionB: "Always let others pick the restaurant", wildSide: "a" },
      { id: "s13", optionA: "Be the organizer of every hangout", optionB: "Be the one who just shows up", wildSide: "b" },
      { id: "s14", optionA: "Never have an awkward silence", optionB: "Never have a disagreement", wildSide: "a" },
      { id: "s15", optionA: "Always text first", optionB: "Always wait for the other person to text", wildSide: "b" },
      { id: "s16", optionA: "Be able to read the room perfectly", optionB: "Be able to command any room", wildSide: "b" },
      { id: "s17", optionA: "Have dinner with your hero", optionB: "Have dinner with your worst enemy", wildSide: "b" },
      { id: "s18", optionA: "Always be the weird friend", optionB: "Always be the normal friend", wildSide: "a" },
      { id: "s19", optionA: "Share your search history with friends", optionB: "Share your notes app with friends", wildSide: "b" },
      { id: "s20", optionA: "Always double-text", optionB: "Always leave people on read", wildSide: "b" },
      { id: "s21", optionA: "Have everyone know your biggest secret", optionB: "Have no one ever know your real feelings", wildSide: "a" },
      { id: "s22", optionA: "Be caught singing in public", optionB: "Be caught dancing in public", wildSide: "b" },
    ],
  },
];

/** Get a deck by slug */
export function getDeckBySlug(slug: string): RatherDeck | undefined {
  return ratherDecks.find((d) => d.slug === slug);
}

/** Get all deck slugs */
export function getAllDeckSlugs(): string[] {
  return ratherDecks.map((d) => d.slug);
}
